// Mocks generated by Mockito 5.4.6 from annotations
// in example/integration_test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:example/domain/models/course.dart' as _i9;
import 'package:example/domain/models/evaluation.dart' as _i3;
import 'package:example/domain/models/peer_evaluation.dart' as _i8;
import 'package:example/domain/models/student.dart' as _i4;
import 'package:example/domain/models/student_home.dart' as _i10;
import 'package:example/domain/models/teacher_data.dart' as _i7;
import 'package:example/domain/models/teacher_insights.dart' as _i2;
import 'package:example/domain/repositories/i_auth_repository.dart' as _i11;
import 'package:example/domain/repositories/i_evaluation_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTeacherInsightsInput_0 extends _i1.SmartFake
    implements _i2.TeacherInsightsInput {
  _FakeTeacherInsightsInput_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvaluation_1 extends _i1.SmartFake implements _i3.Evaluation {
  _FakeEvaluation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudent_2 extends _i1.SmartFake implements _i4.Student {
  _FakeStudent_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IEvaluationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEvaluationRepository extends _i1.Mock
    implements _i5.IEvaluationRepository {
  MockIEvaluationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.Evaluation>> getAll(int? teacherId) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [teacherId]),
            returnValue: _i6.Future<List<_i3.Evaluation>>.value(
              <_i3.Evaluation>[],
            ),
          )
          as _i6.Future<List<_i3.Evaluation>>);

  @override
  _i6.Future<List<_i7.GroupResult>> getGroupResults(int? evalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupResults, [evalId]),
            returnValue: _i6.Future<List<_i7.GroupResult>>.value(
              <_i7.GroupResult>[],
            ),
          )
          as _i6.Future<List<_i7.GroupResult>>);

  @override
  _i6.Future<_i2.TeacherInsightsInput> getTeacherInsightsInput(
    int? teacherId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTeacherInsightsInput, [teacherId]),
            returnValue: _i6.Future<_i2.TeacherInsightsInput>.value(
              _FakeTeacherInsightsInput_0(
                this,
                Invocation.method(#getTeacherInsightsInput, [teacherId]),
              ),
            ),
          )
          as _i6.Future<_i2.TeacherInsightsInput>);

  @override
  _i6.Future<_i3.Evaluation> create({
    required String? name,
    required int? categoryId,
    required int? hours,
    required String? visibility,
    required int? teacherId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #categoryId: categoryId,
              #hours: hours,
              #visibility: visibility,
              #teacherId: teacherId,
            }),
            returnValue: _i6.Future<_i3.Evaluation>.value(
              _FakeEvaluation_1(
                this,
                Invocation.method(#create, [], {
                  #name: name,
                  #categoryId: categoryId,
                  #hours: hours,
                  #visibility: visibility,
                  #teacherId: teacherId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Evaluation>);

  @override
  _i6.Future<void> rename(int? evalId, String? newName, int? teacherId) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [evalId, newName, teacherId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> delete(int? evalId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [evalId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.Evaluation>> getEvaluationsForStudent(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluationsForStudent, [email]),
            returnValue: _i6.Future<List<_i3.Evaluation>>.value(
              <_i3.Evaluation>[],
            ),
          )
          as _i6.Future<List<_i3.Evaluation>>);

  @override
  _i6.Future<_i3.Evaluation?> getLatestForStudent(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestForStudent, [email]),
            returnValue: _i6.Future<_i3.Evaluation?>.value(),
          )
          as _i6.Future<_i3.Evaluation?>);

  @override
  _i6.Future<String?> getGroupNameForStudent(int? evalId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupNameForStudent, [evalId, email]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<_i8.Peer>> getPeersForStudent(int? evalId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getPeersForStudent, [evalId, email]),
            returnValue: _i6.Future<List<_i8.Peer>>.value(<_i8.Peer>[]),
          )
          as _i6.Future<List<_i8.Peer>>);

  @override
  _i6.Future<List<_i9.Course>> getCoursesForStudent(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getCoursesForStudent, [email]),
            returnValue: _i6.Future<List<_i9.Course>>.value(<_i9.Course>[]),
          )
          as _i6.Future<List<_i9.Course>>);

  @override
  _i6.Future<List<_i10.StudentHomeCourse>> getStudentHomeCourses(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentHomeCourses, [email]),
            returnValue: _i6.Future<List<_i10.StudentHomeCourse>>.value(
              <_i10.StudentHomeCourse>[],
            ),
          )
          as _i6.Future<List<_i10.StudentHomeCourse>>);

  @override
  _i6.Future<void> saveResponses({
    required int? evalId,
    required int? evaluatorStudentId,
    required int? evaluatedMemberId,
    required Map<String, int>? scores,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveResponses, [], {
              #evalId: evalId,
              #evaluatorStudentId: evaluatorStudentId,
              #evaluatedMemberId: evaluatedMemberId,
              #scores: scores,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> hasEvaluated({
    required int? evalId,
    required int? evaluatorStudentId,
    required int? evaluatedMemberId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvaluated, [], {
              #evalId: evalId,
              #evaluatorStudentId: evaluatorStudentId,
              #evaluatedMemberId: evaluatedMemberId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasCompletedAllPeers({
    required int? evalId,
    required String? email,
    required int? studentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasCompletedAllPeers, [], {
              #evalId: evalId,
              #email: email,
              #studentId: studentId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i8.CriterionResult>> getMyResults(
    int? evalId,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyResults, [evalId, email]),
            returnValue: _i6.Future<List<_i8.CriterionResult>>.value(
              <_i8.CriterionResult>[],
            ),
          )
          as _i6.Future<List<_i8.CriterionResult>>);

  @override
  _i6.Future<Map<int, Map<String, int>>> getSavedPeerScores({
    required int? evalId,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPeerScores, [], {
              #evalId: evalId,
              #email: email,
            }),
            returnValue: _i6.Future<Map<int, Map<String, int>>>.value(
              <int, Map<String, int>>{},
            ),
          )
          as _i6.Future<Map<int, Map<String, int>>>);

  @override
  _i6.Future<void> testSaveSubmit({
    required String? evaluatorEmail,
    required Map<String, Map<String, int>>? scoresByPeerName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#testSaveSubmit, [], {
              #evaluatorEmail: evaluatorEmail,
              #scoresByPeerName: scoresByPeerName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> readTestTable() =>
      (super.noSuchMethod(
            Invocation.method(#readTestTable, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i11.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Student?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i4.Student?>.value(),
          )
          as _i6.Future<_i4.Student?>);

  @override
  _i6.Future<_i4.Student> register(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i6.Future<_i4.Student>.value(
              _FakeStudent_2(
                this,
                Invocation.method(#register, [name, email, password]),
              ),
            ),
          )
          as _i6.Future<_i4.Student>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Student?> getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue: _i6.Future<_i4.Student?>.value(),
          )
          as _i6.Future<_i4.Student?>);
}
