// =====================
// USERS
// =====================
Table "user" as users {
  _id varchar [not null]
  user_id varchar [primary key, not null]
  name varchar [not null]
  email varchar [not null]
  role varchar [not null]
  created_at timestamp
}

// =====================
// COURSES
// =====================
Table course {
  _id varchar [not null]
  course_id varchar [primary key, not null]
  name varchar [not null]
  nrc varchar
  description text
  created_at timestamp
  created_by varchar [not null, ref: > users.user_id]
}

// =====================
// CATEGORIES (ej: Sprint, Proyecto final)
// =====================
Table category {
  _id varchar [not null]
  category_id varchar [primary key, not null]
  name varchar [not null]
  description varchar [not null]
  course_id varchar [not null, ref: > course.course_id]
}

// =====================
// GROUPS (equipos dentro de cursos)
// =====================
Table "group" as groups {
  _id varchar [not null]
  group_id varchar [primary key, not null]
  name varchar [not null]
  category_id varchar [not null, ref: > category.category_id]
  created_at timestamp
}

// =====================
// USER_COURSE (relación muchos a muchos)
// =====================
Table user_course {
  _id varchar [primary key, not null]
  course_id varchar [not null, ref: > course.course_id]
  user_id varchar [not null, ref: > users.user_id]
  role varchar [not null]
}

// =====================
// USER_GROUP (miembros de equipos)
// =====================
Table user_group {
  _id varchar [primary key, not null]
  user_id varchar [not null, ref: > users.user_id]
  group_id varchar [not null, ref: > groups.group_id]
}

// =====================
// EVALUATIONS
// =====================
Table evaluation {
  _id varchar [not null]
  evaluation_id varchar [primary key, not null]
  title varchar [not null]
  description text [not null]
  start_date timestamp [not null]
  end_date timestamp [not null]
  category_id varchar [not null, ref: > category.category_id]
  created_by varchar [not null, ref: > users.user_id]
}

// =====================
// CRITERIA (criterios de evaluación)
// =====================
Table criterium {
  _id varchar [not null]
  criterium_id varchar [primary key, not null]
  name varchar [not null]
  description text [not null]
  max_score bigint [not null]
}

// =====================
// EVALUATION_CRITERIUM
// =====================
Table evaluation_criterium {
  _id varchar [not null]
  evaluation_id varchar [not null, ref: > evaluation.evaluation_id]
  criterium_id varchar [not null, ref: > criterium.criterium_id]
}

// =====================
// RESULT EVALUATION (una evaluación de A -> B)
// =====================
Table "resultEvaluation" as resultEvaluation {
  resultEvaluation

  _id varchar [not null]
  resultEvaluation_id varchar [primary key, not null]
  evaluation_id varchar [not null, ref: > evaluation.evaluation_id]
  evaluator_id varchar [not null, ref: > users.user_id]
  evaluated_id varchar [not null, ref: > users.user_id]
  comment texts
  created_at timestamp [not null]
  group_id varchar [not null, ref: > groups.group_id]
}

// =====================
// RESULT DETAILS (puntaje por criterio)
// =====================
Table result_criterium {
  _id varchar [not null]
  result_id varchar [not null, ref: > resultEvaluation.resultEvaluation_id]
  criterium_id varchar [not null, ref: > criterium.criterium_id]
  score bigint [not null]
}